### ISSUE TITLE
@import的.less后缀是否强制要求?

### ISSUE THREAD

**Issue by Foolyou** [caizone/code_guide#1]
1. @import语句引用的文件必须写在一对引号内，.less后缀不得省略（与引入css文件时的路径格式一致）。引号使用'和"均可，但在同一项目内必须统一。

咱们项目里的可都是省略了.less的，所以是改规定还是等着改文件呢？@JasinYip

**Comment by JasinYip** [comment]
> .less后缀不得省略

这是哪里得来的结论？LessLint 吗？

**Comment by Foolyou** [comment]
额，这是蔡龙这个code guide里说的。lesslint确实也是这么要求的，不想这么弄的话可以修改一下。

**Comment by JasinYip** [comment]
Less 规范我周一再重新过一遍，我还没时间认真看完呢……

我期望的是统一都不写 `.less`
